// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/tv_show_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i15;

import 'package:ditonton/common/state_enum.dart' as _i10;
import 'package:ditonton/data/models/tv_show/tv_show_episode_model.dart'
    as _i13;
import 'package:ditonton/domain/entities/tv_show/tv_show.dart' as _i11;
import 'package:ditonton/domain/entities/tv_show/tv_show_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_tv_show_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_show_episodes.dart' as _i3;
import 'package:ditonton/domain/usecases/get_tv_show_recommendations.dart'
    as _i4;
import 'package:ditonton/domain/usecases/get_watchlist_tv_show_status.dart'
    as _i5;
import 'package:ditonton/domain/usecases/remove_watchlist_tv_show.dart' as _i7;
import 'package:ditonton/domain/usecases/save_watchlist_tv_show.dart' as _i6;
import 'package:ditonton/presentation/provider/tv_show_detail_notifier.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvShowDetail_0 extends _i1.SmartFake
    implements _i2.GetTvShowDetail {
  _FakeGetTvShowDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvShowEpisodes_1 extends _i1.SmartFake
    implements _i3.GetTvShowEpisodes {
  _FakeGetTvShowEpisodes_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvShowRecommendations_2 extends _i1.SmartFake
    implements _i4.GetTvShowRecommendations {
  _FakeGetTvShowRecommendations_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListStatusTvShow_3 extends _i1.SmartFake
    implements _i5.GetWatchListStatusTvShow {
  _FakeGetWatchListStatusTvShow_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvShow_4 extends _i1.SmartFake
    implements _i6.SaveWatchlistTvShow {
  _FakeSaveWatchlistTvShow_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvShow_5 extends _i1.SmartFake
    implements _i7.RemoveWatchlistTvShow {
  _FakeRemoveWatchlistTvShow_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvShowDetail_6 extends _i1.SmartFake implements _i8.TvShowDetail {
  _FakeTvShowDetail_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvShowDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowDetailNotifier extends _i1.Mock
    implements _i9.TvShowDetailNotifier {
  MockTvShowDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvShowDetail get getTvShowDetail => (super.noSuchMethod(
        Invocation.getter(#getTvShowDetail),
        returnValue: _FakeGetTvShowDetail_0(
          this,
          Invocation.getter(#getTvShowDetail),
        ),
      ) as _i2.GetTvShowDetail);

  @override
  _i3.GetTvShowEpisodes get getTvShowEpisodes => (super.noSuchMethod(
        Invocation.getter(#getTvShowEpisodes),
        returnValue: _FakeGetTvShowEpisodes_1(
          this,
          Invocation.getter(#getTvShowEpisodes),
        ),
      ) as _i3.GetTvShowEpisodes);

  @override
  _i4.GetTvShowRecommendations get getTvShowRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvShowRecommendations),
        returnValue: _FakeGetTvShowRecommendations_2(
          this,
          Invocation.getter(#getTvShowRecommendations),
        ),
      ) as _i4.GetTvShowRecommendations);

  @override
  _i5.GetWatchListStatusTvShow get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchListStatusTvShow_3(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i5.GetWatchListStatusTvShow);

  @override
  _i6.SaveWatchlistTvShow get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistTvShow_4(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i6.SaveWatchlistTvShow);

  @override
  _i7.RemoveWatchlistTvShow get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistTvShow_5(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i7.RemoveWatchlistTvShow);

  @override
  _i8.TvShowDetail get tvShow => (super.noSuchMethod(
        Invocation.getter(#tvShow),
        returnValue: _FakeTvShowDetail_6(
          this,
          Invocation.getter(#tvShow),
        ),
      ) as _i8.TvShowDetail);

  @override
  _i10.RequestState get tvShowState => (super.noSuchMethod(
        Invocation.getter(#tvShowState),
        returnValue: _i10.RequestState.Empty,
      ) as _i10.RequestState);

  @override
  List<_i11.TvShow> get tvShowRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvShowRecommendations),
        returnValue: <_i11.TvShow>[],
      ) as List<_i11.TvShow>);

  @override
  _i10.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i10.RequestState.Empty,
      ) as _i10.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  _i10.RequestState get episodeState => (super.noSuchMethod(
        Invocation.getter(#episodeState),
        returnValue: _i10.RequestState.Empty,
      ) as _i10.RequestState);

  @override
  Map<int, List<_i13.Episode>> get episodesMap => (super.noSuchMethod(
        Invocation.getter(#episodesMap),
        returnValue: <int, List<_i13.Episode>>{},
      ) as Map<int, List<_i13.Episode>>);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i14.Future<void> fetchTvShowDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvShowDetail,
          [id],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> fetchEpisodes(int? tvShowId) => (super.noSuchMethod(
        Invocation.method(
          #fetchEpisodes,
          [tvShowId],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> addWatchlist(_i8.TvShowDetail? tvShow) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvShow],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> removeFromWatchlist(_i8.TvShowDetail? tvShow) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvShow],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
